artifact_location: /home/allen4/work_proj/VISDRONE_DATASET_EVAL/FINAL_PRODUCT/runs/mlflow/316009497993454991
creation_time: 1734482495454
experiment_id: '316009497993454991'
last_update_time: 1734482495454
lifecycle_stage: active
name: visdrone_al_test
