artifact_location: /home/allen4/work_proj/VISDRONE_DATASET_EVAL/FINAL_PRODUCT/runs/mlflow/0
creation_time: 1734482495445
experiment_id: '0'
last_update_time: 1734482495445
lifecycle_stage: active
name: Default
